name: Maven (Kotlin/Java build)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3.4.0
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        architecture: x64
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Prepare artifact
      run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: Package
          path: artifact-from-build-stage
      - name: Get maven version
        id: get-version
        uses: JActions/maven-version@v1.0.1
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: artifact-from-build-stage/*
          name: ${{ steps.get-version.outputs.version }}
          tag_name: ${{ steps.get-version.outputs.version }}
