name: Maven (Kotlin/Java build)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3.4.0
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        architecture: x64
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: Prepare artifact
      run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: Package
      - name: Get maven version
        uses: Deep-Symmetry/github-version-action@v1.1
        with:
          tag-var-name: release_tag
      - name: GitHub Release Action
        uses: 1fxe/GitHub-Release-Action@main
        with:
          release_token: ${{ secrets.RELEASE_TOKEN }}
          release_tag: "$release_tag"
          release_title: "$release_tag"
          release_file: Package
